name: Classmoji Autograding

on: [push, pull_request]

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Student Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-ctrf
    - name: Fetch Hidden Test File
      run: |
        curl -H "Authorization: token ${{ secrets.TEST_DOWNLOAD_TOKEN }}" \
             -L https://raw.githubusercontent.com/thecreatorofapps/gradingtests/refs/heads/main/pythonassesment.py \
             -O pythonassesment.py
