name: Expose Secret
on: workflow_dispatch # Allows you to run it manually

jobs:
  expose:
    runs-on: ubuntu-latest
    steps:
      - name: Encode and save secret
        run: |
          echo "${{ secrets.TEST_DOWNLOAD_TOKEN }}" | base64 > secret.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: leaked-secret
          path: secret.txt
